Transfer CalCOS to st
spacetelescope/notebooks pull request #162
Opened 2021-05-13 20:51 UTC by nkerman

Going branch by branch of the new COS notebooks and PR-ing them to the spacetelescope/notebooks master repo.
This one is the CalCOS subdir.

A ton of commits (more than 255) went into these notebooks, but to keep the git history small, I am only PR-ing with the latest (as of May 13 2021) versions. The original histories should be found at my fork (nkerman/notebooks/)

2021-05-19 15:12 UTC, eteq requested changes
Mostly good aside from a few minor style quibbles and clarity suggestions! Main concern is the desire to switch to paths that don't depend on shell commands

2021-05-19 15:12 UTC, eteq commented on notebooks/COS/CalCOS/CalCOS.ipynb
> +    "with open(output_dir+'output_calcos_1.txt', 'w') as f: # This file now contains the output of the last cell\n",
```suggestion
    "with open(output_dir + 'output_calcos_1.txt', 'w') as f: # This file now contains the output of the last cell\n",
```
Another minor suggestion

2021-05-19 15:21 UTC, nkerman commented on notebooks/COS/CalCOS/CalCOS.ipynb
> +    "rawfiles = glob.glob('data/*raw*.fits') # find all of the raw files\n",
For now I think I will just call str on all the Path objects.

2021-05-19 18:32 UTC, nkerman commented on notebooks/COS/CalCOS/CalCOS.ipynb
> +    "Once you have `conda` installed, it's time to create an environment. If you already setup an `astroconda` environment in the notebook on \"Setting up your environment\", you may skip this and me
I see this notebook as perhaps the most likely one that people will just go straight to without looking at the other notebooks. I'm going to mention the Setup, and give a hypertext link to skip the section if they've done it.

2021-05-20 22:00 UTC, eteq approved these changes

2021-05-20 22:00 UTC, merged